### PR TITLE
Docker updates

### PR DESCRIPTION
**Pull request by srinandan**
Changes to Dockerfile:
1. Move multiple  RUN operations to a single RUN operation
2. Set USER before entrypoint
3. mount volume for plugins

Changes to entrypoint.sh
1. Deprecate `EDGEMICRO_DOCKER`

Changes to edgemicroctl
1. Add Security Context to Deployment.
    a. Set RunAsRoot to false
    b. Set RunAsUser to apigee

### CODE REVIEW

**Comment by vilobhmm** [comment]
@srinandan : Thanks for this change.

Just out of curiosity, how was this tested ? Is there an automated test to verify that the deployment goes through fine or is it more like manually trying out the steps outlined in the Readme.

**Comment by vilobhmm** [comment]
LGTM.

**Comment by srinandan** [comment]
The testing was manual.

**Comment by rajeshm7910** [comment]
LGTM

**Pull request merged**
