### PR TITLE
Apigee Microgateway Installer for Kubernetes

### PR DESCRIPTION
**Pull request by imesh**
This pull request includes an installation guide for Apigee Microgateway to be deployed on Kubernetes.  This revision includes following sections:
- Prerequisites
- Deploy Microgateway on Kubernetes
- Expose Microgateway using a Load Balancer
- Enable Northbound One-Way TLS
- Enable Northbound Two-Way TLS
- Undeploy Microgateway

If required, this can be viewed in Markdown format [here](https://github.com/imesh/microgateway/tree/master/kubernetes/installer). Please review and share your thoughts. Thanks!

### CODE REVIEW

**Comment by imesh** [comment]
Note: The above [travis-ci build failure](https://travis-ci.org/github/apigee-internal/microgateway/jobs/774240256) may have occurred due to a change made in master branch outside this pull request. 

This pull request does not include any code changes, it has introduced a new folder `microgateway/kubernetes/installation-guide/` and added a `README.md` file and a collection of Kubernetes manifests. Thanks!

**Comment by imesh** [comment]
The following improvements were done after discussing the initial implementation with the Microgateway team:

- Removed Istio manifests
- Removed additional Microgateway deployment manifest added for configuring TLS and provided required configurations in the README.md file
- Renamed installation-guide folder to installer and created a folder structure similar to below:
microgateway/kubernetes/installer/manifests/
microgateway/kubernetes/installer/README.md
- Added a deprecation note in the parent README.md file:
microgateway/kubernetes/README.md [Add a deprecation note to refer to the new installer]

**Comment by imesh** [comment]
Added instructions for configuring southbound two-way TLS

**Comment by keyurkarnik** [comment]
@imesh - can you please squash all the commits

**Comment by imesh** [comment]
@keyurkarnik Thanks for asking, I just squashed all 9 commits to a single commit.

**Pull request merged**
