### PR TITLE
bumped to node 12 for edgemicro docker images

### PR DESCRIPTION
**Pull request by boblington**
node 8 is no longer being maintained https://nodejs.org/en/about/releases/

### CODE REVIEW

**Comment by boblington** [comment]
https://nodejs.org/en/about/releases/

**Comment by boblington** [comment]
@googlebot I signed it!

**Comment by boblington** [comment]
checked the CI build looks like there's a misconfiguration in travis? `MOCHA_PASSWORD` not set.

**Comment by keyurkarnik** [comment]
Hey, thanks for the commit, but this change was already done and slated for release.

**Pull request closed without merging**
